//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::credential::Entity as Credential;
pub use super::credential_instance::Entity as CredentialInstance;
pub use super::holder::Entity as Holder;
